name: startupspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  barcode_scan2: ^4.3.0
  card_swiper: ^3.0.1
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  formz: ^0.6.1
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  rive: ^0.9.1
  share_plus: ^9.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/RiveAssets/
