// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0XepQ0dtQ9xm5uqaZUDR34GEoYWhiP4',
    appId: '1:64811816764:web:bb2ada56467bbb56e93039',
    messagingSenderId: '64811816764',
    projectId: 'startupspace-78e1e',
    authDomain: 'startupspace-78e1e.firebaseapp.com',
    storageBucket: 'startupspace-78e1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlyYjNAEUxpi3MwKQ6kYIiJ4S2007GGx8',
    appId: '1:64811816764:android:38698c1bc9a0890ae93039',
    messagingSenderId: '64811816764',
    projectId: 'startupspace-78e1e',
    storageBucket: 'startupspace-78e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyQWQD1Ozk3QOw0rx-iDk0TC3EuaizJs',
    appId: '1:64811816764:ios:939e8d60e1f6fb72e93039',
    messagingSenderId: '64811816764',
    projectId: 'startupspace-78e1e',
    storageBucket: 'startupspace-78e1e.appspot.com',
    iosBundleId: 'com.example.startupspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyQWQD1Ozk3QOw0rx-iDk0TC3EuaizJs',
    appId: '1:64811816764:ios:c3a0066d39a805c6e93039',
    messagingSenderId: '64811816764',
    projectId: 'startupspace-78e1e',
    storageBucket: 'startupspace-78e1e.appspot.com',
    iosBundleId: 'com.example.startupspace.RunnerTests',
  );
}
